name: deploy-container

# Watching a events push and change into the paths
on:
  push:
    branches: ['main']
    paths:
      - 'packages/container/**'

# set execution directory
defaults:
  run:
    working-directory: packages/container

# jobs run parallel by default
jobs:
  # build command
  build:
    # specific version of virtual machine
    runs-on: ubuntu-latest
    # actual command that what to executed
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      # after build
      # access to AWS CLI
      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
